services:
  app:
    build: .
    container_name: ctf_php_app
    ports:
      - "8000:80"
    environment:
      - DATABASE_URL=${DATABASE_URL}
    volumes:
      - ./:/var/www/html
    depends_on:
      - db
  db:
    image: postgres:15
    container_name: ctf_postgres
    restart: unless-stopped
    environment:
      - POSTGRES_DB=${PGDATABASE}
      - POSTGRES_USER=${PGUSER}
      - POSTGRES_PASSWORD=${PGPASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
volumes:
  pg_data:
